# Generated by Django 5.2.9 on 2025-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco Mensal')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Anual')),
                ('max_employees', models.IntegerField(default=50, verbose_name='Limite de Funcionarios')),
                ('max_forms', models.IntegerField(default=10, verbose_name='Limite de Formularios Ativos')),
                ('max_reports', models.IntegerField(default=20, verbose_name='Relatorios por Mes')),
                ('data_retention_days', models.IntegerField(default=365, verbose_name='Retencao de Dados (dias)')),
                ('has_pdf_export', models.BooleanField(default=True, verbose_name='Exportacao PDF')),
                ('has_csv_import', models.BooleanField(default=True, verbose_name='Importacao CSV')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Acesso API')),
                ('has_custom_branding', models.BooleanField(default=True, verbose_name='Personalizacao Visual')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='Suporte Prioritario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibicao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CANCELLED', 'Cancelada'), ('EXPIRED', 'Expirada'), ('SUSPENDED', 'Suspensa')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('start_date', models.DateField(verbose_name='Data de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Termino')),
                ('is_yearly', models.BooleanField(default=False, verbose_name='Assinatura Anual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-created_at'],
            },
        ),
    ]
