# Generated by Django 6.0.3 on 2026-04-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentorder'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentorder',
            new_name='billing_pay_stripe__6870d9_idx',
            old_name='billing_pay_stripe__idx',
        ),
    ]
