# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customplanrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=99, help_text='Valor base do plano', max_digits=10, verbose_name='Preço Base (R$)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='default_billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('SEMESTRAL', 'Semestral')], default='SEMESTRAL', max_length=10, verbose_name='Ciclo Padrão'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_pct_corporate',
            field=models.DecimalField(decimal_places=2, default=15, help_text='Percentual de desconto para 20+ funcionários', max_digits=5, verbose_name='Desconto 20+ func. (%)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='discount_pct_small',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Percentual de desconto para 6-20 funcionários', max_digits=5, verbose_name='Desconto 6-20 func. (%)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='min_employees_discount',
            field=models.IntegerField(default=6, help_text='A partir de quantos funcionários aplica desconto', verbose_name='Mín. Func. Desconto'),
        ),
        migrations.AddField(
            model_name='plan',
            name='per_employee_price',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Valor adicional por funcionário', max_digits=8, verbose_name='Valor por Funcionário (R$)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_semestral',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Semestral'),
        ),
        migrations.AddField(
            model_name='plan',
            name='pricing_mode',
            field=models.CharField(choices=[('FIXED', 'Preço Fixo'), ('DYNAMIC', 'Base + Por Funcionário')], default='FIXED', max_length=10, verbose_name='Modo de Pricing'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('SEMESTRAL', 'Semestral'), ('YEARLY', 'Anual')], default='SEMESTRAL', max_length=10, verbose_name='Ciclo de Cobrança'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='calculated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço calculado com base no número de funcionários', max_digits=10, null=True, verbose_name='Preço Calculado'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='employee_count_at_subscription',
            field=models.IntegerField(default=0, help_text='Número de funcionários no momento da assinatura', verbose_name='Func. na Contratação'),
        ),
    ]
