[phases.setup]
nixPkgs = [
    "python311", 
    "git",
    "pango",
    "cairo",
    "glib",
    "gdk-pixbuf",
    "libffi",
    "fontconfig",
    "pkg-config",
    "gcc"
]
aptPkgs = [
    "shared-mime-info",
    "libgobject-2.0-0"
]

[variables]
PYTHONUNBUFFERED = "1"
LD_LIBRARY_PATH = "/usr/lib:/usr/local/lib:/nix/var/nix/profiles/default/lib"
