[phases.setup]
aptPkgs = ["...", "libgirepository1.0-dev", "libpango1.0-dev", "libopenjp2-7-dev", "libffi-dev", "libcairo2", "shared-mime-info"]
nixPkgs = ["...", "pango", "glib", "fontconfig", "cairo"]
