# Generated by Django 6.0.4 on 2026-05-04 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_website_url'),
        ('forms_builder', '0003_formquestion_analysis_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=150, verbose_name='Setor / Departamento')),
                ('funcao', models.CharField(max_length=150, verbose_name='Função / Cargo')),
                ('atividade', models.CharField(max_length=300, verbose_name='Atividade')),
                ('descricao_perigo', models.TextField(verbose_name='Descrição do Perigo')),
                ('fonte_geradora', models.CharField(blank=True, max_length=300, verbose_name='Fonte Geradora')),
                ('tipo_risco', models.CharField(choices=[('FISICO', 'Físico'), ('QUIMICO', 'Químico'), ('BIOLOGICO', 'Biológico'), ('ERGONOMICO', 'Ergonômico'), ('PSICOSSOCIAL', 'Psicossocial'), ('ACIDENTE', 'Acidente / Mecânico')], default='PSICOSSOCIAL', max_length=20, verbose_name='Tipo de Risco')),
                ('norma_referencia', models.CharField(choices=[('NR-1', 'NR-1 — GRO/PGR'), ('NR-7', 'NR-7 — PCMSO'), ('NR-12', 'NR-12 — Máquinas'), ('NR-17', 'NR-17 — Ergonomia'), ('OUTRA', 'Outra')], default='NR-1', max_length=10, verbose_name='Norma de Referência')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('MITIGATED', 'Mitigado'), ('ELIMINATED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('identified_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Identificação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='companies.company', verbose_name='Empresa')),
                ('form_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazards', to='forms_builder.forminstance', verbose_name='Formulário de Origem')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_hazards', to=settings.AUTH_USER_MODEL, verbose_name='Identificado por')),
            ],
            options={
                'verbose_name': 'Registro de Perigo',
                'verbose_name_plural': 'Registros de Perigos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Probabilidade (1-5)')),
                ('severidade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Severidade (1-5)')),
                ('nivel_risco', models.CharField(blank=True, choices=[('TRIVIAL', 'Trivial'), ('TOLERAVEL', 'Tolerável'), ('MODERADO', 'Moderado'), ('SUBSTANCIAL', 'Substancial'), ('INTOLERAVEL', 'Intolerável')], max_length=20, verbose_name='Nível de Risco')),
                ('score', models.IntegerField(default=0, verbose_name='Score (P×S)')),
                ('justificativa', models.TextField(blank=True, verbose_name='Justificativa da Avaliação')),
                ('data_avaliacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('avaliado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado por')),
                ('hazard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='risk_management.hazardregistry', verbose_name='Perigo')),
            ],
            options={
                'verbose_name': 'Avaliação de Risco',
                'verbose_name_plural': 'Avaliações de Risco',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='ControlMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ELIMINACAO', '1. Eliminação'), ('SUBSTITUICAO', '2. Substituição'), ('ENGENHARIA', '3. Engenharia'), ('ADMINISTRATIVA', '4. Administrativa'), ('EPI', '5. EPI'), ('EPC', '5. EPC')], default='ADMINISTRATIVA', max_length=20, verbose_name='Tipo de Controle')),
                ('descricao', models.TextField(verbose_name='Descrição da Medida')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo de Implementação')),
                ('implementada', models.BooleanField(default=False, verbose_name='Implementada?')),
                ('data_implementacao', models.DateField(blank=True, null=True, verbose_name='Data de Implementação')),
                ('eficacia_verificada', models.BooleanField(default=False, verbose_name='Eficácia Verificada?')),
                ('data_verificacao', models.DateField(blank=True, null=True, verbose_name='Data de Verificação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_measures', to='risk_management.riskassessment', verbose_name='Avaliação de Risco')),
            ],
            options={
                'verbose_name': 'Medida de Controle',
                'verbose_name_plural': 'Medidas de Controle',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da Ação')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('responsavel', models.CharField(max_length=200, verbose_name='Responsável')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('prazo_inicio', models.DateField(blank=True, null=True, verbose_name='Prazo de Início')),
                ('prazo_fim', models.DateField(verbose_name='Prazo de Conclusão')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão Efetiva')),
                ('indicador_eficacia', models.TextField(blank=True, help_text='Como a eficácia será medida (ex: reaplicação SIMDCCONR01)', verbose_name='Indicador de Eficácia')),
                ('percentual_conclusao', models.IntegerField(default=0, verbose_name='% Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('risk_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='risk_management.riskassessment', verbose_name='Avaliação de Risco')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['-prazo_fim'],
            },
        ),
    ]
