# Generated by Django 6.0.4 on 2026-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardregistry',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='Gerado Automaticamente'),
        ),
        migrations.AddField(
            model_name='hazardregistry',
            name='source_dimension',
            field=models.CharField(blank=True, help_text='Dimensão do questionário que originou este perigo', max_length=100, verbose_name='Dimensão de Origem'),
        ),
        migrations.AddField(
            model_name='hazardregistry',
            name='source_instrument',
            field=models.CharField(blank=True, help_text='IMCO, FDAC, NR-01, NR-17, NR-12', max_length=30, verbose_name='Instrumento de Origem'),
        ),
        migrations.AddField(
            model_name='hazardregistry',
            name='source_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Média da dimensão no momento da geração', max_digits=4, null=True, verbose_name='Score de Origem'),
        ),
        migrations.AlterField(
            model_name='hazardregistry',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pendente de Revisão'), ('ACTIVE', 'Ativo'), ('MITIGATED', 'Mitigado'), ('ELIMINATED', 'Eliminado')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
