# Generated by Django 5.2.9 on 2025-12-04 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('COMPLETED', 'Concluido'), ('FAILED', 'Falhou')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total de Linhas')),
                ('success_count', models.IntegerField(default=0, verbose_name='Importados com Sucesso')),
                ('error_count', models.IntegerField(default=0, verbose_name='Erros')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='Detalhes dos Erros')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='Importado por')),
            ],
            options={
                'verbose_name': 'Log de Importacao',
                'verbose_name_plural': 'Logs de Importacao',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Corporativo')),
                ('cpf', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='CPF deve conter 11 digitos numericos', regex='^\\d{11}$')], verbose_name='CPF')),
                ('setor', models.CharField(max_length=100, verbose_name='Setor/Departamento')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('turno', models.CharField(choices=[('MORNING', 'Manha'), ('AFTERNOON', 'Tarde'), ('NIGHT', 'Noite'), ('FULL', 'Integral'), ('ROTATING', 'Revezamento')], default='FULL', max_length=20, verbose_name='Turno')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissao')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('matricula', models.CharField(blank=True, max_length=50, verbose_name='Matricula')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo'), ('ON_LEAVE', 'Afastado'), ('TERMINATED', 'Desligado')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company', verbose_name='Empresa')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinados', to='employees.employee', verbose_name='Gestor Imediato')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['nome'],
                'unique_together': {('company', 'cpf'), ('company', 'email')},
            },
        ),
    ]
