# Generated by Django 6.0.3 on 2026-04-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='centro_de_custo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Centro de Custo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='data_demissao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Demissao'),
        ),
    ]
