# Generated by Django 6.0.4 on 2026-05-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_centro_de_custo_employee_data_demissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
