# Generated by Django 6.0.3 on 2026-04-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingconfig',
            name='ticker_text',
            field=models.TextField(default='Condição Especial: Desconto Exclusivo nos Planos | Acesso Imediato | SIMDCCONR01 — Líder em Riscos Psicossociais', verbose_name='Texto do Ticker (Faixa Superior)'),
        ),
    ]
