# Generated by Django 6.0.3 on 2026-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_landingconfig_ticker_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfig',
            name='pro_price',
            field=models.DecimalField(decimal_places=2, default=2250, max_digits=8, verbose_name='Preço Professional'),
        ),
        migrations.AlterField(
            model_name='landingconfig',
            name='starter_price',
            field=models.DecimalField(decimal_places=2, default=420, max_digits=8, verbose_name='Preço Starter'),
        ),
    ]
