# Generated by Django 6.0.4 on 2026-05-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_persistence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfig',
            name='hero_image_db',
            field=models.BinaryField(blank=True, null=True, verbose_name='Imagem Hero em Banco'),
        ),
        migrations.AlterField(
            model_name='landingconfig',
            name='hero_image_mime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type Hero'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_db',
            field=models.BinaryField(blank=True, null=True, verbose_name='Avatar em Banco'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar_mime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type Avatar'),
        ),
    ]
