# Generated by Django 6.0.4 on 2026-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_alter_landingconfig_hero_image_db_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('role', models.CharField(max_length=150, verbose_name='Ramo/Especialidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, verbose_name='Link de redirecionamento')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo da Empresa')),
                ('logo_db', models.BinaryField(blank=True, null=True, verbose_name='Logo em Banco')),
                ('logo_mime', models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type Logo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Parceiro de Desenvolvimento',
                'verbose_name_plural': 'Parceiros de Desenvolvimento',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
