# Generated by Django 6.0.4 on 2026-05-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_developmentpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingconfig',
            name='whatsapp_number',
            field=models.CharField(default='11920881521', max_length=20, verbose_name='WhatsApp (apenas números)'),
        ),
    ]
