# Generated by Django 6.0.4 on 2026-05-04 20:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_website_url'),
        ('forms_builder', '0003_formquestion_analysis_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Snapshot')),
                ('overall_score', models.DecimalField(decimal_places=2, default=3.5, max_digits=4, verbose_name='Score Geral (1-5)')),
                ('overall_classification', models.CharField(default='Adequado', max_length=20, verbose_name='Classificação Geral')),
                ('dimension_scores', models.JSONField(blank=True, default=dict, help_text='{"IMCO|Liderança": 3.5, "FDAC|Fairness": 2.8, ...}', verbose_name='Scores por Dimensão')),
                ('sector_scores', models.JSONField(blank=True, default=dict, help_text='{"Administrativo": 4.1, "Operacional": 2.9, ...}', verbose_name='Scores por Setor')),
                ('risk_count_by_type', models.JSONField(blank=True, default=dict, help_text='{"critico": 5, "atencao": 12, "adequado": 30, "forte": 10}', verbose_name='Riscos por Tipo')),
                ('total_respondentes', models.IntegerField(default=0, verbose_name='Total de Respondentes')),
                ('total_itens_analisados', models.IntegerField(default=0, verbose_name='Total de Itens Analisados')),
                ('pcmso_alertas', models.IntegerField(default=0, verbose_name='Alertas PCMSO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_snapshots', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('form_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_snapshots', to='forms_builder.forminstance', verbose_name='Formulário de Origem')),
            ],
            options={
                'verbose_name': 'Snapshot de Evolução',
                'verbose_name_plural': 'Snapshots de Evolução',
                'ordering': ['-snapshot_date'],
                'unique_together': {('company', 'form_instance')},
            },
        ),
        migrations.CreateModel(
            name='DimensionEvolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrumento', models.CharField(max_length=20, verbose_name='Instrumento')),
                ('dimensao', models.CharField(max_length=100, verbose_name='Dimensão')),
                ('media', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Média')),
                ('classificacao', models.CharField(max_length=20, verbose_name='Classificação')),
                ('total_respostas', models.IntegerField(default=0, verbose_name='Total de Respostas')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_evolutions', to='companies.company', verbose_name='Empresa')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_details', to='evolution.evolutionsnapshot', verbose_name='Snapshot')),
            ],
            options={
                'verbose_name': 'Evolução por Dimensão',
                'verbose_name_plural': 'Evoluções por Dimensão',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RiskScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data')),
                ('score', models.IntegerField(default=50, verbose_name='Score de Risco (0-100)')),
                ('faixa', models.CharField(blank=True, choices=[('BAIXO', 'Baixo Risco (0-30)'), ('MEDIO', 'Médio Risco (31-70)'), ('ALTO', 'Alto Risco (71+)')], max_length=10, verbose_name='Faixa de Risco')),
                ('score_fisico', models.IntegerField(default=0, verbose_name='Score Físico')),
                ('score_quimico', models.IntegerField(default=0, verbose_name='Score Químico')),
                ('score_biologico', models.IntegerField(default=0, verbose_name='Score Biológico')),
                ('score_ergonomico', models.IntegerField(default=0, verbose_name='Score Ergonômico')),
                ('score_psicossocial', models.IntegerField(default=0, verbose_name='Score Psicossocial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score_history', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Histórico de Score de Risco',
                'verbose_name_plural': 'Históricos de Score de Risco',
                'ordering': ['-date'],
            },
        ),
    ]
