# Generated by Django 5.2.9 on 2025-12-04 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=150, verbose_name='Sobrenome')),
                ('role', models.CharField(choices=[('ADMIN_MASTER', 'Administrador Master'), ('COMPANY_ADMIN', 'Administrador da Empresa'), ('EMPLOYEE', 'Funcionario')], default='EMPLOYEE', max_length=20, verbose_name='Papel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso ao Admin')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Termos Aceitos')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite dos Termos')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='Politica de Privacidade Aceita')),
                ('privacy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aceite da Politica')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-date_joined'],
            },
        ),
    ]
