# Generated by Django (manually) to match models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lgpd_individual_accepted',
            field=models.BooleanField(default=False, verbose_name='Consentimento Individual (Analise)'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_individual_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Consentimento Individual'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_aggregate_accepted',
            field=models.BooleanField(default=False, verbose_name='Consentimento Agregado (PGR/GRO)'),
        ),
        migrations.AddField(
            model_name='user',
            name='lgpd_aggregate_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Consentimento Agregado'),
        ),
    ]
