# Generated by Django 6.0.3 on 2026-04-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_professional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='privacy_accepted',
            field=models.BooleanField(default=False, verbose_name='Privacidade Aceita'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Aceite Privacidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Aceite Termos'),
        ),
    ]
