# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_privacy_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='professional_crea',
            field=models.CharField(blank=True, help_text='Para Técnicos de Segurança', max_length=50, verbose_name='Registro CREA/CFT'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_crm',
            field=models.CharField(blank=True, help_text='Para Médicos do Trabalho', max_length=50, verbose_name='Registro CRM'),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_specialty',
            field=models.CharField(blank=True, max_length=150, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_MASTER', 'Administrador Master'), ('COMPANY_ADMIN', 'Administrador da Empresa'), ('MEDICO', 'Médico do Trabalho'), ('TECNICO_SEG', 'Técnico de Segurança'), ('EMPLOYEE', 'Funcionario')], default='EMPLOYEE', max_length=20, verbose_name='Papel'),
        ),
    ]
