# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models, connection

def add_professional_columns(apps, schema_editor):
    """Adiciona colunas profissionais de forma segura (compatível com colunas pré-existentes)."""
    with connection.cursor() as cursor:
        columns = [col.name for col in connection.introspection.get_table_description(cursor, 'accounts_user')]
        
        if 'professional_crea' not in columns:
            cursor.execute("ALTER TABLE accounts_user ADD COLUMN professional_crea varchar(50) DEFAULT '';")
        
        if 'professional_crm' not in columns:
            cursor.execute("ALTER TABLE accounts_user ADD COLUMN professional_crm varchar(50) DEFAULT '';")
            
        if 'professional_specialty' not in columns:
            cursor.execute("ALTER TABLE accounts_user ADD COLUMN professional_specialty varchar(150) DEFAULT '';")


def remove_professional_columns(apps, schema_editor):
    """Remove colunas se reverter."""
    if connection.vendor != 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE accounts_user DROP COLUMN IF EXISTS professional_crea;")
            cursor.execute("ALTER TABLE accounts_user DROP COLUMN IF EXISTS professional_crm;")
            cursor.execute("ALTER TABLE accounts_user DROP COLUMN IF EXISTS professional_specialty;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_privacy_accepted_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_professional_columns, remove_professional_columns),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='user',
                    name='professional_crea',
                    field=models.CharField(blank=True, help_text='Para Técnicos de Segurança', max_length=50, verbose_name='Registro CREA/CFT'),
                ),
                migrations.AddField(
                    model_name='user',
                    name='professional_crm',
                    field=models.CharField(blank=True, help_text='Para Médicos do Trabalho', max_length=50, verbose_name='Registro CRM'),
                ),
                migrations.AddField(
                    model_name='user',
                    name='professional_specialty',
                    field=models.CharField(blank=True, max_length=150, verbose_name='Especialidade'),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN_MASTER', 'Administrador Master'), ('COMPANY_ADMIN', 'Administrador da Empresa'), ('MEDICO', 'Médico do Trabalho'), ('TECNICO_SEG', 'Técnico de Segurança'), ('EMPLOYEE', 'Funcionario')], default='EMPLOYEE', max_length=20, verbose_name='Papel'),
        ),
    ]
