# Generated by Django 6.0.4 on 2026-05-04 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_website_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NRSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_risco', models.CharField(choices=[('FISICO', 'Físico'), ('QUIMICO', 'Químico'), ('BIOLOGICO', 'Biológico'), ('ERGONOMICO', 'Ergonômico'), ('PSICOSSOCIAL', 'Psicossocial'), ('ACIDENTE', 'Acidente / Mecânico')], max_length=20, verbose_name='Tipo de Risco')),
                ('nivel_risco_minimo', models.CharField(choices=[('TRIVIAL', 'Trivial'), ('TOLERAVEL', 'Tolerável'), ('MODERADO', 'Moderado'), ('SUBSTANCIAL', 'Substancial'), ('INTOLERAVEL', 'Intolerável')], default='MODERADO', help_text='Sugestão ativada a partir deste nível', max_length=20, verbose_name='Nível Mínimo de Risco')),
                ('norma_referencia', models.CharField(default='NR-1', help_text='NR-1, NR-7, NR-12, NR-17', max_length=20, verbose_name='Norma de Referência')),
                ('categoria', models.CharField(choices=[('PREVENCAO', 'Medida de Prevenção'), ('AMBIENTE', 'Ajuste de Ambiente'), ('EPI', 'EPI Recomendado'), ('EPC', 'EPC Recomendado'), ('TREINAMENTO', 'Treinamento'), ('ORGANIZACIONAL', 'Medida Organizacional'), ('ACOMPANHAMENTO', 'Acompanhamento Médico')], default='PREVENCAO', max_length=20, verbose_name='Categoria')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título da Sugestão')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('fundamentacao', models.TextField(blank=True, help_text='Referência ao artigo da NR ou autor teórico', verbose_name='Fundamentação Legal/Teórica')),
                ('prioridade', models.IntegerField(default=5, help_text='1 = mais prioritária', verbose_name='Prioridade de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Sugestão NR',
                'verbose_name_plural': 'Sugestões NR',
                'ordering': ['prioridade', 'tipo_risco'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trend_type', models.CharField(choices=[('SECTOR_DECLINE', 'Setor em Declínio'), ('RISK_GROWING', 'Risco Crescente'), ('SCORE_PROJECTION', 'Projeção de Score'), ('DIMENSION_ALERT', 'Dimensão em Risco'), ('EMPLOYEE_PATTERN', 'Padrão Individual')], max_length=30, verbose_name='Tipo de Tendência')),
                ('confidence', models.CharField(choices=[('HIGH', 'Alta Confiança'), ('MEDIUM', 'Média Confiança'), ('LOW', 'Baixa Confiança')], default='MEDIUM', max_length=10, verbose_name='Confiança')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('recomendacao', models.TextField(verbose_name='Recomendação Sugerida')),
                ('setor', models.CharField(blank=True, max_length=150, verbose_name='Setor Afetado')),
                ('dimensao', models.CharField(blank=True, max_length=150, verbose_name='Dimensão Afetada')),
                ('score_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score Atual')),
                ('score_projetado', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Score Projetado')),
                ('data_points', models.JSONField(blank=True, default=list, help_text='Histórico de scores usados na projeção', verbose_name='Dados da Análise')),
                ('is_acknowledged', models.BooleanField(default=False, verbose_name='Reconhecido')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconhecido em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_predictions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_alerts', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Alerta Preditivo',
                'verbose_name_plural': 'Alertas Preditivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
