# Generated by Django 5.2.9 on 2025-12-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('forms_builder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('report_type', models.CharField(choices=[('FORM_RESULTS', 'Resultados de Formulario'), ('PERIOD_SUMMARY', 'Resumo do Periodo'), ('CLIMATE_INDEX', 'Indice de Clima'), ('WELLBEING_INDEX', 'Indice de Bem-estar'), ('NR01_COMPLIANCE', 'Compliance NR-01'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Periodo Inicio')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Periodo Fim')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Arquivo PDF')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parametros')),
                ('results_data', models.JSONField(blank=True, default=dict, verbose_name='Dados do Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='Gerado por')),
                ('form_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='forms_builder.forminstance', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Relatorio',
                'verbose_name_plural': 'Relatorios',
                'ordering': ['-created_at'],
            },
        ),
    ]
