# Generated by Django 5.2.9 (manually)

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo de Validacao')),
                ('diagnostic_data', models.JSONField(default=dict, verbose_name='Dados do Laudo (Groq)')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Gerado em')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic', to='forms_builder.formassignment', verbose_name='Formulario Respondido')),
            ],
            options={
                'verbose_name': 'Laudo Individual',
                'verbose_name_plural': 'Laudos Individuais',
                'ordering': ['-generated_at'],
            },
        ),
    ]
