# Generated by Django (manually) to match models

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_employeediagnostic'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='Assinado Digitalmente'),
        ),
        migrations.AddField(
            model_name='report',
            name='signature_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados da Assinatura'),
        ),
        migrations.AddField(
            model_name='report',
            name='signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('FORM_RESULTS', 'Resultados de Formulario'), ('PERIOD_SUMMARY', 'Resumo do Periodo'), ('CLIMATE_INDEX', 'Indice de Clima'), ('WELLBEING_INDEX', 'Indice de Bem-estar'), ('NR01_COMPLIANCE', 'Compliance NR-01'), ('SIMDCCONR01', 'Laudo Integrado SIMDCCONR01'), ('LAUDO_PERICIAL', 'Laudo Pericial Assinado'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Tipo'),
        ),
    ]
