# Generated by Django 6.0.3 on 2026-04-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_employeediagnostic_signature_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeediagnostic',
            name='assigned_professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_diagnostics', to=settings.AUTH_USER_MODEL, verbose_name='Signatario Atribuido'),
        ),
        migrations.AlterField(
            model_name='employeediagnostic',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_diagnostics_final', to=settings.AUTH_USER_MODEL),
        ),
    ]
