# Generated by Django 6.0.3 on 2026-04-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_departmentdiagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signerprofile',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Upload da imagem com a assinatura manuscrita (PNG transparente recomendado)', null=True, upload_to='signatures/professionals/', verbose_name='Imagem da Assinatura'),
        ),
    ]
