# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models, connection


def add_signature_base64_column(apps, schema_editor):
    with connection.cursor() as cursor:
        cols = [col.name for col in connection.introspection.get_table_description(cursor, 'reports_signerprofile')]
        if 'signature_base64' not in cols:
            cursor.execute("ALTER TABLE reports_signerprofile ADD COLUMN signature_base64 text DEFAULT '';")


def remove_signature_base64_column(apps, schema_editor):
    if connection.vendor != 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE reports_signerprofile DROP COLUMN IF EXISTS signature_base64;")


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_signerprofile_signature_image'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_signature_base64_column, remove_signature_base64_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='signerprofile',
                    name='signature_base64',
                    field=models.TextField(blank=True, default='', help_text='Imagem da assinatura salva como data URI base64 para persistência', verbose_name='Assinatura (Base64)'),
                ),
            ]
        ),
    ]
