# Generated by Django 6.0.4 on 2026-05-04 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_website_url'),
        ('reports', '0009_signerprofile_signature_base64'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LAUDO', 'Laudo Pericial'), ('AET', 'Análise Ergonômica do Trabalho'), ('AEP', 'Avaliação Ergonômica Preliminar'), ('PCMSO', 'PCMSO — Programa de Controle Médico'), ('PGR', 'PGR — Programa de Gerenciamento de Riscos'), ('PPRA', 'PPRA (Legado)'), ('LTCAT', 'LTCAT'), ('OUTRO', 'Outro')], default='LAUDO', max_length=20, verbose_name='Tipo de Documento')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/', verbose_name='Arquivo')),
                ('versao', models.IntegerField(default=1, verbose_name='Versão')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Vigente'), ('SUPERSEDED', 'Substituído'), ('EXPIRED', 'Expirado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('normas_aplicadas', models.JSONField(blank=True, default=list, help_text='Ex: ["NR-1 (2024.1)", "NR-7 (2024.1)", "NR-17 (2024.1)"]', verbose_name='Normas Aplicadas')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='documents.document', verbose_name='Versão Anterior')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='reports.report', verbose_name='Relatório de Origem')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.IntegerField(verbose_name='Versão')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documents/versions/%Y/%m/', verbose_name='Arquivo da Versão')),
                ('alterado_em', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em')),
                ('motivo_alteracao', models.TextField(blank=True, verbose_name='Motivo da Alteração')),
                ('alterado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_history', to='documents.document', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Versão de Documento',
                'verbose_name_plural': 'Versões de Documentos',
                'ordering': ['-versao'],
            },
        ),
    ]
