# Generated by Django 6.0.4 on 2026-05-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='arquivo_db',
            field=models.BinaryField(blank=True, null=True, verbose_name='Arquivo em Banco'),
        ),
        migrations.AddField(
            model_name='document',
            name='arquivo_mime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='document',
            name='arquivo_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='arquivo_db',
            field=models.BinaryField(blank=True, null=True, verbose_name='Arquivo em Banco'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='arquivo_mime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='arquivo_nome',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo'),
        ),
    ]
