# Generated by Django 5.2.9 on 2025-12-04 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_anonymous', models.BooleanField(default=False, help_text='Se ativado, respostas nao serao vinculadas aos funcionarios', verbose_name='Anonimo')),
                ('start_date', models.DateTimeField(verbose_name='Data de Inicio')),
                ('end_date', models.DateTimeField(verbose_name='Data de Termino')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('ACTIVE', 'Ativo'), ('CLOSED', 'Encerrado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('target_sectors', models.JSONField(blank=True, default=list, help_text='Lista de setores. Vazio = todos', verbose_name='Setores Alvo')),
                ('target_positions', models.JSONField(blank=True, default=list, help_text='Lista de cargos. Vazio = todos', verbose_name='Cargos Alvo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_instances', to='companies.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Formulario Aplicado',
                'verbose_name_plural': 'Formularios Aplicados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Andamento'), ('COMPLETED', 'Concluido'), ('EXPIRED', 'Expirado')], default='PENDING', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluido em')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='employees.employee', verbose_name='Funcionario')),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='forms_builder.forminstance', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Atribuicao de Formulario',
                'verbose_name_plural': 'Atribuicoes de Formularios',
                'ordering': ['-form_instance__created_at'],
                'unique_together': {('form_instance', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Template')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('category', models.CharField(choices=[('NR01', 'NR-01 - Riscos Ocupacionais'), ('CLIMATE', 'Clima Organizacional'), ('WELLBEING', 'Bem-estar no Trabalho'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Categoria')),
                ('is_global', models.BooleanField(default=False, verbose_name='Template Global')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('company', models.ForeignKey(blank=True, help_text='Deixe vazio para templates globais', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_templates', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Template de Formulario',
                'verbose_name_plural': 'Templates de Formularios',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto da Pergunta')),
                ('question_type', models.CharField(choices=[('SCALE', 'Escala (1-5)'), ('SCALE_10', 'Escala (1-10)'), ('MULTIPLE', 'Multipla Escolha'), ('SINGLE', 'Escolha Unica'), ('TEXT', 'Texto Aberto'), ('YESNO', 'Sim/Nao'), ('DATE', 'Data'), ('NUMBER', 'Numero')], max_length=20, verbose_name='Tipo de Resposta')),
                ('options', models.JSONField(blank=True, default=list, help_text='Lista de opcoes para multipla escolha', verbose_name='Opcoes')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obrigatoria')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Texto de Ajuda')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms_builder.formtemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='forminstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='forms_builder.formtemplate', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, verbose_name='Resposta Texto')),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Numerico')),
                ('selected_options', models.JSONField(blank=True, default=list, verbose_name='Opcoes Selecionadas')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='Valor Booleano')),
                ('date_value', models.DateField(blank=True, null=True, verbose_name='Valor Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Respondido em')),
                ('anonymous_employee', models.ForeignKey(blank=True, help_text='Usado apenas para registro de participacao em formularios anonimos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_answers', to='employees.employee', verbose_name='Funcionario (Anonimo)')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms_builder.formassignment', verbose_name='Atribuicao')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms_builder.formquestion', verbose_name='Pergunta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'unique_together': {('assignment', 'question')},
            },
        ),
    ]
