# Generated by Django (manually) to match models

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='category',
            field=models.CharField(choices=[('NR01', 'NR-01 - Riscos Ocupacionais'), ('CLIMATE', 'Clima Organizacional'), ('WELLBEING', 'Bem-estar no Trabalho'), ('SIMDCCONR01', 'Sistema Integrado SIMDCCONR01'), ('CUSTOM', 'Personalizado')], max_length=20, verbose_name='Categoria'),
        ),
    ]
