# Generated by Django 6.0.4 on 2026-05-04 20:07

from django.db import migrations, models, connection


def add_analysis_category_column(apps, schema_editor):
    with connection.cursor() as cursor:
        cols = [col.name for col in connection.introspection.get_table_description(cursor, 'forms_builder_formquestion')]
        if 'analysis_category' not in cols:
            cursor.execute("ALTER TABLE forms_builder_formquestion ADD COLUMN analysis_category varchar(20) DEFAULT 'DIAGNOSTICO';")


def remove_analysis_category_column(apps, schema_editor):
    if connection.vendor != 'sqlite':
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE forms_builder_formquestion DROP COLUMN IF EXISTS analysis_category;")


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0002_category_update'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_analysis_category_column, remove_analysis_category_column),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='formquestion',
                    name='analysis_category',
                    field=models.CharField(choices=[('DIAGNOSTICO', 'Diagnóstico Psicossocial'), ('DISSONANCIA', 'Dissonância de Clima e Cultura'), ('RISCOS', 'Riscos Identificados (PGR/GRO)'), ('RECOMENDACOES', 'Recomendações de Ação')], default='DIAGNOSTICO', help_text='Define em qual seção do laudo esta pergunta será agrupada', max_length=20, verbose_name='Categoria de Análise'),
                ),
            ]
        ),
    ]
