# Generated by Django 6.0.4 on 2026-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0003_formquestion_analysis_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Templates bloqueados não podem ter perguntas alteradas. Usado para o SIMDCCONR01 (160 itens).', verbose_name='Bloqueado (Imutável)'),
        ),
    ]
