# Generated by Django 5.2.9 on 2025-12-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Criacao'), ('UPDATE', 'Atualizacao'), ('DELETE', 'Exclusao'), ('VIEW', 'Visualizacao'), ('EXPORT', 'Exportacao'), ('IMPORT', 'Importacao'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('APPROVE', 'Aprovacao'), ('REJECT', 'Rejeicao'), ('PUBLISH', 'Publicacao'), ('SUBMIT', 'Envio')], max_length=20, verbose_name='Acao')),
                ('description', models.TextField(verbose_name='Descricao')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereco IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
