# Generated by Django 6.0.4 on 2026-05-04 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_company_website_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RISK_HIGH', 'Risco Alto Detectado'), ('RISK_CRITICAL', 'Risco Crítico Identificado'), ('DEADLINE_APPROACHING', 'Prazo Vencendo'), ('DEADLINE_OVERDUE', 'Prazo Vencido'), ('REPORT_EXPIRING', 'Laudo Expirando'), ('HEALTH_DROP', 'Queda no Índice de Saúde'), ('SCORE_DECLINE', 'Score de Risco Piorou'), ('PAYMENT_DUE', 'Pagamento Pendente'), ('FORM_LOW_RESPONSE', 'Baixa Adesão ao Formulário'), ('PCMSO_ALERT', 'Alerta PCMSO')], max_length=30, verbose_name='Tipo')),
                ('severidade', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Atenção'), ('CRITICAL', 'Crítico')], default='WARNING', max_length=10, verbose_name='Severidade')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lido')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('is_email_sent', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('related_object_type', models.CharField(blank=True, max_length=100, verbose_name='Tipo do Objeto')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lido em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='companies.company', verbose_name='Empresa')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'is_read'], name='alerts_aler_company_f848b1_idx'), models.Index(fields=['tipo', 'is_resolved'], name='alerts_aler_tipo_432451_idx')],
            },
        ),
    ]
