# Generated by Django 5.2.9 on 2025-12-04 15:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razao Social')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CNPJ deve conter 14 digitos numericos', regex='^\\d{14}$')], verbose_name='CNPJ')),
                ('responsavel_nome', models.CharField(max_length=200, verbose_name='Nome do Responsavel')),
                ('responsavel_email', models.EmailField(max_length=254, verbose_name='Email do Responsavel')),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Telefone deve conter 10 ou 11 digitos', regex='^\\d{10,11}$')], verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=300, verbose_name='Endereco')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='Estado')),
                ('cep', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('cor_primaria', models.CharField(default='#0d6efd', max_length=7, verbose_name='Cor Primaria')),
                ('cor_secundaria', models.CharField(default='#6c757d', max_length=7, verbose_name='Cor Secundaria')),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando Aprovacao'), ('ACTIVE', 'Ativa'), ('SUSPENDED', 'Suspensa'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('configs', models.JSONField(blank=True, default=dict, verbose_name='Configuracoes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_companies', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='billing.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Conteudo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Comunicado',
                'verbose_name_plural': 'Comunicados',
                'ordering': ['-created_at'],
            },
        ),
    ]
