# Generated by Django 6.0.3 on 2026-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fim do Periodo Atual'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Mensal Customizado'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Anual Customizado'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Cliente Stripe'),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Assinatura Stripe'),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(default='inactive', max_length=50, verbose_name='Status Assinatura'),
        ),
    ]
