# Generated by Django 6.0.3 on 2026-04-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_current_period_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contratante_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF do Contratante'),
        ),
        migrations.AddField(
            model_name='company',
            name='contratante_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Contratante'),
        ),
        migrations.AddField(
            model_name='company',
            name='data_aceite_contrato',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Assinatura'),
        ),
    ]
