# Generated by Antigravity on 2026-04-23

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_contratante_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo_db',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logo em Banco'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type'),
        ),
    ]
