# Generated by Antigravity on 2026-04-23
import mimetypes
import os
from django.db import migrations

def populate_logo_db(apps, schema_editor):
    Company = apps.get_model('companies', 'Company')
    for company in Company.objects.all():
        if company.logo and not company.logo_db:
            try:
                # Tenta ler o arquivo do storage
                # Nota: usamos storage.open para ser compatível com local e cloud
                with company.logo.open('rb') as f:
                    company.logo_db = f.read()
                    company.logo_mime_type = mimetypes.guess_type(company.logo.name)[0] or 'image/png'
                    company.save()
            except Exception as e:
                print(f"Erro ao migrar logo da empresa {company.nome_fantasia}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_logo_db_company_logo_mime_type'),
    ]

    operations = [
        migrations.RunPython(populate_logo_db, reverse_code=migrations.RunPython.noop),
    ]
