# Generated by Django 6.0.4 on 2026-05-21 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, help_text='Se pertence a um grupo empresarial (Multi-CNPJ)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='companies.company', verbose_name='Empresa Matriz'),
        ),
    ]
